import { Toaster } from "@/components/ui/sonner";
import "@/lib/constants/config";
import Providers from "@/providers";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import "./prototypes";

const outfitSans = Outfit({
	weight: "variable",
	display: "swap",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Home",
	description: "Generated by Azuri Technologies",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${outfitSans.className} antialiased`}>
				<Providers>
					<div className="flex flex-col overflow-hidden">
						{children}
					</div>
					<Toaster richColors={true} />
				</Providers>
			</body>
		</html>
	);
}
