# https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid
name: Azure Static Web Apps CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - main

jobs:
    build_and_deploy_job:
        if: github.event_name == 'push' ||
            (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: ubuntu-latest
        environment: Production
        name: Build and Deploy Job
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true
                  lfs: false

            - name: Install OIDC Client from Core Package
              run: npm install @actions/core@1.6.0 @actions/http-client

            - name: Get Id Token
              uses: actions/github-script@v6
              id: idtoken
              with:
                  script: |
                      const core = require('@actions/core');
                      return await core.getIDToken();
                  result-encoding: string

            - name: Build And Deploy
              env:
                  DATABASE_URL_HPBASE: ${{ secrets.DATABASE_URL_HPBASE }}
                  DATABASE_URL_PROPOSALS: ${{ secrets.DATABASE_URL_PROPOSALS }}
                  GENERATE_SOURCEMAP: ${{ secrets.GENERATE_SOURCEMAP }}
                  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
                  NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
                  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
                  NEXT_PUBLIC_CONTACT_EMAIL: ${{ secrets.NEXT_PUBLIC_CONTACT_EMAIL }}
                  SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
                  NOREPLY_HOST: ${{ secrets.NOREPLY_HOST }}
                  NOREPLY_PORT: ${{ secrets.NOREPLY_PORT }}
                  NOREPLY_EMAIL: ${{ secrets.NOREPLY_EMAIL }}
                  NOREPLY_PASSWORD: ${{ secrets.NOREPLY_PASSWORD }}
                  NEXT_PUBLIC_MAINTENANCE_MODE: ${{ secrets.NEXT_PUBLIC_MAINTENANCE_MODE }}
                  STORAGE_PATH: ${{ secrets.STORAGE_PATH }}
                  NEXT_PUBLIC_AZURE_STORAGE_URL: ${{ secrets.NEXT_PUBLIC_AZURE_STORAGE_URL }}
                  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
                  AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
                  AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
                  CI: ${{ secrets.CI }}
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_DUNE_05CD0FD03 }}
                  action: upload
                  app_build_command: "npm run prisma-init && npm run build"
                  app_location: "/" # your Next.js root
                  api_location: "" # hybrid SSR mode
                  output_location: "" # auto-detect .next
                  github_id_token: ${{ steps.idtoken.outputs.result }}

    close_pull_request_job:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
            - name: Close Pull Request
              id: closepullrequest
              uses: Azure/static-web-apps-deploy@v1
              with:
                  action: close
