# https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid
name: Azure Static Web Apps CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - main

jobs:
    build_and_deploy_job:
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: ubuntu-latest
        environment: Production
        name: Build and Deploy Job
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true
                  lfs: false
            - name: Build and Deploy
              env:
                  DATABASE_URL_HPBASE: ${{ secrets.DATABASE_URL_HPBASE }}
                  DATABASE_URL_PROPOSALS: ${{ secrets.DATABASE_URL_PROPOSALS }}
                  GENERATE_SOURCEMAP: ${{ secrets.GENERATE_SOURCEMAP }}
                  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
                  NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
                  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
                  NEXT_PUBLIC_CONTACT_EMAIL: ${{ secrets.NEXT_PUBLIC_CONTACT_EMAIL }}
                  SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
                  NOREPLY_HOST: ${{ secrets.NOREPLY_HOST }}
                  NOREPLY_PORT: ${{ secrets.NOREPLY_PORT }}
                  NOREPLY_EMAIL: ${{ secrets.NOREPLY_EMAIL }}
                  NOREPLY_PASSWORD: ${{ secrets.NOREPLY_PASSWORD }}
                  NEXT_PUBLIC_MAINTENANCE_MODE: ${{ secrets.NEXT_PUBLIC_MAINTENANCE_MODE }}
                  STORAGE_PATH: ${{ secrets.STORAGE_PATH }}
                  NEXT_PUBLIC_AZURE_STORAGE_URL: ${{ secrets.NEXT_PUBLIC_AZURE_STORAGE_URL }}
                  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
                  AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
                  AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
                  CI: ${{ secrets.CI }}
                  DEVELOPMENT_BRAZIL_EMAIL: ${{ secrets.DEVELOPMENT_BRAZIL_EMAIL }}
                  PROJECTS_BRAZIL_EMAIL: ${{ secrets.PROJECTS_BRAZIL_EMAIL }}
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_POND_0609AB303 }}
                  action: "upload"
                  ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
                  # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
                  app_build_command: "npm ci && npm run build"
                  app_location: "/" # App source code path
                  api_build_command: >
                      rm -rf $SOURCE_DIR/node_modules/@next/swc-* &&
                      rm -rf $SOURCE_DIR/.next/cache
                  output_location: "." # Built app content directory - optional
                  ###### End of Repository/Build Configurations ######

    close_pull_request_job:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
            - name: Close Pull Request
              id: closepullrequest
              uses: Azure/static-web-apps-deploy@v1
              with:
                  action: "close"
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_POND_0609AB303 }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }}


